name: Generate Asci Artwork
on: push
jobs:
    ascii_job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4
        - name: Executin Shell Script
          run: |
            chmod +x Ascii-script.sh
            ./Ascii-script.sh
        - name: List Repo File
          run: ls -ltra
            
            