name: exploring variables and secrets
on: push
env:
  container_reg: docker.io
  docker_username: emanshehta99
  image_name: github-actions-nginx
jobs:
  docker: 
    runs-on: ubuntu-latest
    steps:
    - name: docker build
      run: echo docker build -t $container_reg/$docker_username/$image_name:latest .
    - name: docker login
      env:
        docker_pass: Eman@1999
      run: echo docker login --username=$docker_username --password:$docker_pass   
    - name: docker publish
      run: docker push $container_reg/$docker_username/$image_name:latest
  deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
    - name: docker run
      run: docker run -d -p 80808:80   $container_reg/$docker_username/$image_name:latest    